CURRENT_FOLDER=$(pwd);
SCRIPT_FOLDER=$(realpath $(dirname "${0}"));
CODE_FOLDER="${SCRIPT_FOLDER}/code";

STANDALONE_GRADLE="${SCRIPT_FOLDER}/standalone-gradle";
STANDALONE_GRADLE_MODULES="${STANDALONE_GRADLE}/modules";
STANDALONE_GRADLE_THEMES="${STANDALONE_GRADLE}/themes";
STANDALONE_GRADLE_WARS="${STANDALONE_GRADLE}/wars";

STANDALONE_MAVEN="${SCRIPT_FOLDER}/standalone-maven";
STANDALONE_MAVEN_MODULES="${STANDALONE_MAVEN}/modules";
STANDALONE_MAVEN_THEMES="${STANDALONE_MAVEN}/themes";
STANDALONE_MAVEN_WARS="${STANDALONE_MAVEN}/wars";

WORKSPACE_GRADLE="${SCRIPT_FOLDER}/workspace-gradle";
WORKSPACE_GRADLE_MODULES="${WORKSPACE_GRADLE}/modules";
WORKSPACE_GRADLE_THEMES="${WORKSPACE_GRADLE}/themes";
WORKSPACE_GRADLE_WARS="${WORKSPACE_GRADLE}/wars";

WORKSPACE_MAVEN="${SCRIPT_FOLDER}/workspace-maven";
WORKSPACE_MAVEN_MODULES="${WORKSPACE_MAVEN}/modules";
WORKSPACE_MAVEN_THEMES="${WORKSPACE_MAVEN}/themes";
WORKSPACE_MAVEN_WARS="${WORKSPACE_MAVEN}/wars";

COLOR_OFF="\033[0m"
COLOR_RED="\033[0;31m"
COLOR_GREEN="\033[0;32m"
COLOR_YELLOW="\033[0;33m"
COLOR_BLUE="\033[0;34m"

COLOR_GREEN_BG="\033[0;30;42m"
COLOR_YELLOW_BG="\033[0;43m"
COLOR_BLUE_BG="\033[0;30;44m"

SAMPLE_FILE_NAME=".sample"
SAMPLES=()